baseURL = "https://demo.creativebulma.net/components/tooltip/1.2/"
languageCode = "en-us"
title = "BulmaTooltip"
theme = "creativebulma"
[markup]
  [markup.highlight]
    style = "manni"

[params]
  version = "1.1"

[menu]

  [[menu.main]]
    identifier = "how-to"
    name = "How-To"
    url = "#"
    weight = 20